a1 = input("Enter 1 hobby")
a2 = input("Enter 1 hobby")
a3 = input("Enter 1 hobby")
a4 = input("Enter 1 hobby")
a5 = input("Enter 1 hobby")
a6 = input("Enter 1 hobby")
a7 = input("Enter 1 hobby")
a8 = input("Enter 1 hobby")
list = [a1,a2,a3,a4,a5,a6,a7,a8]
# list.append(a1)
# list.append(a2)
# list.append(a3)
# list.append(a4)
# list.append(a5)
# list.append(a6)
# list.append(a7)
# list.append(a8)
print(list)
